/**@type {import('@docusaurus/plugin-content-docs').SidebarsConfig}*/

const sidebars = {
  stickySidebar: [
    "sticky/intro",
    "sticky/template-structure",
    "sticky/secondary-classes",
    "sticky/color-highlights-backgrounds",
    "sticky/menus-main",
    "sticky/menus",
    "sticky/pwa",
    {
      type: "category",
      label: "المان ها",
      items: [
        "sticky/components/main-card-style",
        "sticky/components/accordions",
        "sticky/components/action-sheets-modals",
        "sticky/components/ads",
        "sticky/components/go-to-up",
        "sticky/components/breadcrumb",
        "sticky/components/icons-btns",
        "sticky/components/cards",
        "sticky/components/carousel",
        "sticky/components/charts",
        "sticky/components/chips",
        "sticky/components/collapse",
        "sticky/components/columns",
        "sticky/components/device-detection",
        "sticky/components/disqus",
        "sticky/components/dividers",
        "sticky/components/embed",
        "sticky/components/upload",
        "sticky/components/location",
        "sticky/components/inputs",
        "sticky/components/images",
        "sticky/components/link-lists-groups",
        "sticky/components/notif-alerts",
        "sticky/components/offline-detection",
        "sticky/components/preloaders",
        "sticky/components/qrcode",
        "sticky/components/sharing",
        "sticky/components/search",
        "sticky/components/sidebar",
        "sticky/components/snackbars",
        "sticky/components/tabs",
        "sticky/components/toasts",
        "sticky/components/toggles-switches",
        "sticky/components/vibrate",
        "sticky/components/ending-words",
      ],
    },
    {
      type: "category",
      label: "صفحات",
      items: [
        "sticky/pages/pages",
        "sticky/pages/component-built-pages",
        "sticky/pages/full-screen-pages",
        "sticky/pages/galleries",
      ],
    },
    "sticky/faq",
  ],
  appkitSidebar: [
    "appkit/intro",
    "appkit/template-structure",
    "appkit/secondary-classes",
    "appkit/color-highlights-backgrounds",
    "appkit/menus-main",
    "appkit/menus",
    "appkit/pwa",
    {
      type: "category",
      label: "المان ها",
      items: [
        "appkit/components/main-card-style",
        "appkit/components/accordions",
        "appkit/components/action-sheets-modals",
        "appkit/components/ads",
        "appkit/components/go-to-up",
        "appkit/components/breadcrumb",
        "appkit/components/icons-btns",
        "appkit/components/cards",
        "appkit/components/carousel",
        "appkit/components/charts",
        "appkit/components/chips",
        "appkit/components/collapse",
        "appkit/components/columns",
        "appkit/components/device-detection",
        "appkit/components/disqus",
        "appkit/components/dividers",
        "appkit/components/embed",
        "appkit/components/upload",
        "appkit/components/location",
        "appkit/components/inputs",
        "appkit/components/images",
        "appkit/components/link-lists-groups",
        "appkit/components/notif-alerts",
        "appkit/components/offline-detection",
        "appkit/components/preloaders",
        "appkit/components/qrcode",
        "appkit/components/sharing",
        "appkit/components/search",
        "appkit/components/sidebar",
        "appkit/components/snackbars",
        "appkit/components/tabs",
        "appkit/components/toasts",
        "appkit/components/toggles-switches",
        "appkit/components/vibrate",
        "appkit/components/ending-words",
      ],
    },
    {
      type: "category",
      label: "صفحات",
      items: [
        "appkit/pages/pages",
        "appkit/pages/component-built-pages",
        "appkit/pages/full-screen-pages",
        "appkit/pages/galleries",
      ],
    },
    "appkit/faq",
  ],
  duoSidebar: [
    "duo/intro",
    "duo/template-structure",
    "duo/secondary-classes",
    "duo/color-highlights-backgrounds",
    "duo/menus-main",
    "duo/menus",
    "duo/pwa",
    {
      type: "category",
      label: "المان ها",
      items: [
        "duo/components/main-card-style",
        "duo/components/accordions",
        "duo/components/action-sheets-modals",
        "duo/components/ads",
        "duo/components/go-to-up",
        "duo/components/breadcrumb",
        "duo/components/icons-btns",
        "duo/components/cards",
        "duo/components/carousel",
        "duo/components/charts",
        "duo/components/chips",
        "duo/components/collapse",
        "duo/components/columns",
        "duo/components/device-detection",
        "duo/components/disqus",
        "duo/components/dividers",
        "duo/components/embed",
        "duo/components/upload",
        "duo/components/location",
        "duo/components/inputs",
        "duo/components/images",
        "duo/components/link-lists-groups",
        "duo/components/notif-alerts",
        "duo/components/offline-detection",
        "duo/components/preloaders",
        "duo/components/qrcode",
        "duo/components/sharing",
        "duo/components/search",
        "duo/components/sidebar",
        "duo/components/snackbars",
        "duo/components/tabs",
        "duo/components/toasts",
        "duo/components/toggles-switches",
        "duo/components/vibrate",
        "duo/components/ending-words",
      ],
    },
    {
      type: "category",
      label: "صفحات",
      items: [
        "duo/pages/pages",
        "duo/pages/component-built-pages",
        "duo/pages/full-screen-pages",
        "duo/pages/galleries",
      ],
    },
    "duo/faq",
  ],
  elansazSidebar: [
    "elansaz-whmcs-module/install",
    "elansaz-whmcs-module/configuration",
  ],
};

export default sidebars;
