/**@type {import('@docusaurus/plugin-content-docs').SidebarsConfig}*/

const sidebars = {
  pwaSidebar: [
    {
      type: "category",
      label: "اپکیت",
      items: [
        "appkit/intro",
        "appkit/template-structure",
        "appkit/secondary-classes",
        "appkit/color-highlights-backgrounds",
        "appkit/menus-main",
        "appkit/menus",
        "appkit/pwa",
        "appkit/faq",
        {
          type: "category",
          label: "المان ها",
          items: [
            "appkit/components/main-card-style",
            "appkit/components/accordions",
            "appkit/components/action-sheets-modals",
            "appkit/components/ads",
            "appkit/components/go-to-up",
            "appkit/components/breadcrumb",
            "appkit/components/icons-btns",
            "appkit/components/cards",
            "appkit/components/carousel",
            "appkit/components/charts",
            "appkit/components/chips",
            "appkit/components/collapse",
            "appkit/components/columns",
            "appkit/components/device-detection",
            "appkit/components/disqus",
            "appkit/components/dividers",
            "appkit/components/embed",
            "appkit/components/upload",
            "appkit/components/location",
            "appkit/components/inputs",
            "appkit/components/images",
            "appkit/components/link-lists-groups",
            "appkit/components/notif-alerts",
            "appkit/components/offline-detection",
            "appkit/components/preloaders",
            "appkit/components/qrcode",
            "appkit/components/sharing",
            "appkit/components/search",
            "appkit/components/sidebar",
            "appkit/components/snackbars",
            "appkit/components/tabs",
            "appkit/components/toasts",
            "appkit/components/toggles-switches",
            "appkit/components/vibrate",
            "appkit/components/ending-words",
          ],
        },
        {
          type: "category",
          label: "صفحات",
          items: [
            "appkit/pages/pages",
            "appkit/pages/component-built-pages",
            "appkit/pages/full-screen-pages",
            "appkit/pages/galleries",
          ],
        },
      ],
    },
  ],
  whmcsSidebar: ["hostlar/intro"],
};

export default sidebars;
